# Generated by Django 4.1.1 on 2022-10-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tiltle',
            new_name='title',
        ),
    ]
